# Moonraker Configuration File

[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/oscar/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*

[machine]
provider: systemd_dbus

[file_manager]
enable_object_processing: True

[octoprint_compat]

[webcam camera]
location: printer
service: mjpegstreamer
target_fps: 15
stream_url: /webcam/?action=stream
snapshot_url: /webcam/?action=snapshot

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager klipper]
type: git_repo
path: ~/klipper
origin: https://github.com/Klipper3d/klipper.git
managed_services: klipper

[update_manager moonraker]
type: git_repo
path: ~/moonraker
origin: https://github.com/Arksine/moonraker.git
managed_services: moonraker

